//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeBuilder_Auxilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_account()
        {
            this.te_team = new HashSet<te_team>();
        }
    
        public string acc_Name { get; set; }
        public string acc_mail { get; set; }
        public string acc_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<te_team> te_team { get; set; }
    }
}
