//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeBuilder_Auxilium.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokeBankEntities : DbContext
    {
        public PokeBankEntities()
            : base("name=PokeBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_ability> a_ability { get; set; }
        public virtual DbSet<acc_account> acc_account { get; set; }
        public virtual DbSet<dc_damageClass> dc_damageClass { get; set; }
        public virtual DbSet<i_item> i_item { get; set; }
        public virtual DbSet<m_move> m_move { get; set; }
        public virtual DbSet<me_moveEffect> me_moveEffect { get; set; }
        public virtual DbSet<n_nature> n_nature { get; set; }
        public virtual DbSet<p_pokemon> p_pokemon { get; set; }
        public virtual DbSet<s_stat> s_stat { get; set; }
        public virtual DbSet<t_type> t_type { get; set; }
        public virtual DbSet<te_team> te_team { get; set; }
        public virtual DbSet<te_typeEfficiacy> te_typeEfficiacy { get; set; }
        public virtual DbSet<tp_teampokemon> tp_teampokemon { get; set; }
    }
}
