//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeBuilder_Auxilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_stat
    {
        public int p_pokemon_p_id { get; set; }
        public int s_stat1 { get; set; }
        public int s_value { get; set; }
    
        public virtual p_pokemon p_pokemon { get; set; }
    }
}
