//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeBuilder_Auxilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class te_typeEfficiacy
    {
        public int t_type_t_IdAt { get; set; }
        public int t_type_t_IdDe { get; set; }
        public Nullable<int> t_damagePercentage { get; set; }
    
        public virtual t_type t_type { get; set; }
        public virtual t_type t_type1 { get; set; }
    }
}
